language: ruby

cache:
  bundler: true
  directories:
    - .onceover

script: bundler exec onceover run spec --debug
bundler_args: --without development --path vendor/bundle

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
