language: ruby
cache:
  bundler: true
  directories:
    - 'controlrepo_cache'
env:
  - CONTROLREPO_temp="controlrepo_cache"
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
script: bundler exec rake controlrepo_spec
bundler_args: --without acceptance
