language: ruby
cache:
  bundler: true
  directories:
    - .controlrepo
env:
  #- CONTROLREPO_temp="controlrepo_cache"
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
script: bundler exec controlrepo run spec
bundler_args: --without acceptance
