language: ruby
cache:
  bundler: true
  directories:
    - .controlrepo
env:
  #- CONTROLREPO_temp="controlrepo_cache"
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
script: bundler exec controlrepo run spec
bundler_args: --without acceptance, development
