language: ruby

cache:
  bundler: true
  directories:
    - .onceover

script: bundler exec onceover run spec
bundler_args: --without development --path vendor/bundle

env:
  - PUPPET_version='4.5.0'
  - PUPPET_version='4.0.0'
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
matrix:
  include:
    - rvm: 2.1.8
      env: PUPPET_version='3.8.7'
    - rvm: 2.1.8
      env: PUPPET_version='3.7.5'
    - rvm: 2.1.8
      env: PUPPET_version='3.4.3'
    - rvm: 2.1.8
      env: PUPPET_version='3.3.2'
